// createSlice: 
// is a function provided by Redux Toolkit for creating Redux slices.

// Redux slices:
// are pieces of the Redux state and the associated actions and reducers.

import { createSlice } from "@reduxjs/toolkit";



const initialState = { // This defines the initial state of our BMI slice with default values.
    weight: "",
    height: "",
    bmi: null,
    message: "",
};

// Creates bmiSlice using the createSlice function. 
// It specifies the initial state and defines three reducer functions: setWeight, setHeight, and calculateBMI. 
// These reducers will handle corresponding actions dispatched by the application to update the BMI state.
const bmiSlice = createSlice({
    name: "bmi",
    initialState,
    reducers: {
        setWeight(state, action){
            state.weight = action.payload;
        },
        setHeight(state, action){
            state.height = action.payload;
        },
        // No action payload for calculateBMI, because it doesn't require any additional data from the action payload. Instead, 
        // it calculates the BMI based on the current state's weight and height properties.
        calculateBMI(state){
            const heightToMeter = state.height / 100
            const bmiValue = state.weight / (heightToMeter * heightToMeter)
            
            let bmiMessage = "";

            if (bmiValue < 18.5){
            bmiMessage = "Underweight";
            } else if (bmiValue >= 18.5 && bmiValue < 24.9){
            bmiMessage = "Normal weight";
            } else if (bmiValue >= 25 && bmiValue < 29.9 ) {
            bmiMessage = "Overweight";
            } else {
            bmiMessage = "Obese";
            }

            state.bmi = bmiValue.toFixed(2);
            state.message = bmiMessage;
        },
    },
});

// Exporting the action creators generated by the createSlice function. 
export const { setWeight, setHeight, calculateBMI } = bmiSlice.actions;
export default bmiSlice.reducer;